// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"cesium/EllipsoidFadeMaterialProperty":{"path":"cesium/EllipsoidFadeMaterialProperty","id":"cesium/EllipsoidFadeMaterialProperty","file":"cesium/EllipsoidFadeMaterialProperty.ts"},"cesium/EllipsoidFadeMaterialEntity":{"path":"cesium/EllipsoidFadeMaterialEntity","id":"cesium/EllipsoidFadeMaterialEntity","file":"cesium/EllipsoidFadeMaterialEntity.ts"},"cesium/createPropertyDescriptor":{"path":"cesium/createPropertyDescriptor","id":"cesium/createPropertyDescriptor","file":"cesium/createPropertyDescriptor.ts"},"cesium/getValueOrClonedDefault":{"path":"cesium/getValueOrClonedDefault","id":"cesium/getValueOrClonedDefault","file":"cesium/getValueOrClonedDefault.ts"},"cesium/EllipsoidFadeMaterial":{"path":"cesium/EllipsoidFadeMaterial","id":"cesium/EllipsoidFadeMaterial","file":"cesium/EllipsoidFadeMaterial.ts"},"graphics/Draw/special":{"path":"graphics/Draw/special","id":"graphics/Draw/special","file":"graphics/Draw/special.ts"},"graphics/Draw/surface":{"path":"graphics/Draw/surface","id":"graphics/Draw/surface","file":"graphics/Draw/surface.ts"},"graphics/Draw/cube":{"path":"graphics/Draw/cube","id":"graphics/Draw/cube","file":"graphics/Draw/cube.ts"},"graphics/Draw/line":{"path":"graphics/Draw/line","id":"graphics/Draw/line","file":"graphics/Draw/line.ts"},"graphics/index":{"path":"graphics","id":"graphics/index","file":"graphics/index.tsx"},"cesium/index":{"path":"cesium","id":"cesium/index","file":"cesium/index.tsx"},"index":{"path":"/","id":"index","file":"index.tsx"}},
    routeComponents: {
'cesium/EllipsoidFadeMaterialProperty': React.lazy(() => import(/* webpackChunkName: "cesium_EllipsoidFadeMaterialProperty" */'../../../src/pages/cesium/EllipsoidFadeMaterialProperty.ts')),
'cesium/EllipsoidFadeMaterialEntity': React.lazy(() => import(/* webpackChunkName: "cesium_EllipsoidFadeMaterialEntity" */'../../../src/pages/cesium/EllipsoidFadeMaterialEntity.ts')),
'cesium/createPropertyDescriptor': React.lazy(() => import(/* webpackChunkName: "cesium_createPropertyDescriptor" */'../../../src/pages/cesium/createPropertyDescriptor.ts')),
'cesium/getValueOrClonedDefault': React.lazy(() => import(/* webpackChunkName: "cesium_getValueOrClonedDefault" */'../../../src/pages/cesium/getValueOrClonedDefault.ts')),
'cesium/EllipsoidFadeMaterial': React.lazy(() => import(/* webpackChunkName: "cesium_EllipsoidFadeMaterial" */'../../../src/pages/cesium/EllipsoidFadeMaterial.ts')),
'graphics/Draw/special': React.lazy(() => import(/* webpackChunkName: "graphics_Draw_special" */'../../../src/pages/graphics/Draw/special.ts')),
'graphics/Draw/surface': React.lazy(() => import(/* webpackChunkName: "graphics_Draw_surface" */'../../../src/pages/graphics/Draw/surface.ts')),
'graphics/Draw/cube': React.lazy(() => import(/* webpackChunkName: "graphics_Draw_cube" */'../../../src/pages/graphics/Draw/cube.ts')),
'graphics/Draw/line': React.lazy(() => import(/* webpackChunkName: "graphics_Draw_line" */'../../../src/pages/graphics/Draw/line.ts')),
'graphics/index': React.lazy(() => import(/* webpackChunkName: "graphics_index" */'../../../src/pages/graphics/index.tsx')),
'cesium/index': React.lazy(() => import(/* webpackChunkName: "cesium_index" */'../../../src/pages/cesium/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "index" */'../../../src/pages/index.tsx')),
},
  };
}
