// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as Cesium from 'cesium';

window.CESIUM_BASE_URL = '/Cesium';
Cesium.Ion.defaultAccessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3NTRhMmI1NS0yZmRmLTRhMGMtOTYxNi04OTM3OGVkYTRjYjYiLCJpZCI6OTczMDAsImlhdCI6MTY1NTEwNzI1NH0.LB89i36BMZMVOmOhTJ5DkVGGbEX4RSKaXUgbDTxQkoo';

export { Cesium };
